### ISSUE TITLE
Unauthenticated user receives data for offline attack

### ISSUE THREAD

**Issue by Sc00bz** [agix/secretin#2]
"getUser" takes a username and returns the private key encrypted with the user's password. You can use this data to make offline password guesses. The cost is currently one round of SHA256 and one AES block decrypt (or encrypt).

**Comment by agix** [comment]
I know that and it's a "feature". I want no authentication on the server. Actually, server saved version is just a way to store your DB. You should be able to got back your DB and use it in offline mode with the standalone version. Just like keepass with your DB.

It's the weakness in the concept, maybe it's to weak to rely only on user password. Maybe there is a better way to do but without server side authentication I didn't find...

**Comment by Sc00bz** [comment]
Why do you not want server side authentication?

If you do not see anything wrong with this image you should not be writing security software. With just a username you get the password encrypted private key and the full encrypted database.

![wtf](https://cloud.githubusercontent.com/assets/2030592/10319781/a2ec1226-6c35-11e5-8d99-db37b6e1db9e.png)

**Comment by agix** [comment]
Yes I know but I don't want to rely on server side stuff. The main point is to provide something anybody can compromise (at the first time I tried to code a js lib that would push the DB on public github...).

Think like server DB is compromised at any time... It's one of the main concept, no trust on server side, trust only your browser.

That's why I also provide the standalone version (not working with the recent design but I'll fix it tomorrow) where you have to save the JSON DB by your own way (just like you do with your keepass keystore).

Also as I said to you on twitter, it's more a POC of using w3c crypto API than a real project with a future in software security but I thank you to give me advice to improve it.

I'll personnaly use it because I can get my passwords from any modern browser (mobile or not) without extension or third party application but I'm aware anybody can bruteforce my password offline.

**Comment by agix** [comment]
At least I can try to decrypt the private key with the submitted password to prevent sending everything to everyone but it means server side crypto (I already transgressed this rule with the challenge to manage the rights)

**Comment by Sc00bz** [comment]
What? no, don't send the password. At least do this. (Note there are better ways like PAKE.)

---

Client:

```
encryptionKey = PW-KDF(password, ...)
authKey = SHA256(encryptionKey)
Send(authKey)
```

Server:

```
authKey = Receive()
if (SHA256(authKey) == storedHash)
    Send(privateKey)
else
    Error
```

**Comment by agix** [comment]
Ok should be implemented now.

As I said PBKDF2 is not implemented yet so I used 10 000 SHA256 on the salted password. I choose to save salt in the DB and you can add a private static salt.

https://github.com/agix/secretin/blob/waiting_for/server/index.js#L134

Server respond random bytes if you ask for a user without knowing the hash of the derivedKey.
